"""Create Cart and Book tables

Revision ID: 2e7273cc439a
Revises: 
Create Date: 2026-03-12 22:27:09.558627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e7273cc439a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('Genre')
    #op.drop_table('Review')
    #op.drop_table('Store_Book')
    #op.drop_table('Orders')
    #op.drop_table('Payment')
    #op.drop_table('BookAuthor')
    #op.drop_index(op.f('email'), table_name='User')
    #op.drop_table('User')
    #op.drop_table('Author')
    #op.drop_table('Store')
    #op.drop_table('Delivery')
    op.alter_column('Book', 'title',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Book', 'stock_quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    #op.drop_constraint(op.f('book_ibfk_1'), 'Book', type_='foreignkey')
    op.add_column('Cart', sa.Column('delivery_date', sa.DateTime(), nullable=False))
    op.add_column('Cart', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    op.add_column('Cart', sa.Column('delivery_method', sa.String(length=50), nullable=True))
    op.add_column('Cart', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('Cart', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Cart', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_Cart_cart_id'), 'Cart', ['cart_id'], unique=False)
    #op.drop_constraint(op.f('cart_ibfk_1'), 'Cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('cart_ibfk_1'), 'Cart', 'User', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_Cart_cart_id'), table_name='Cart')
    op.alter_column('Cart', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Cart', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('Cart', 'status')
    op.drop_column('Cart', 'delivery_method')
    op.drop_column('Cart', 'delivery_address')
    op.drop_column('Cart', 'delivery_date')
    op.create_foreign_key(op.f('book_ibfk_1'), 'Book', 'Genre', ['genre_id'], ['genre_id'])
    op.alter_column('Book', 'stock_quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Book', 'title',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.create_table('Delivery',
    sa.Column('delivery_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', mysql.DATETIME(), nullable=False),
    sa.Column('delivery_address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('delivery_method', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], name=op.f('delivery_ibfk_1')),
    sa.PrimaryKeyConstraint('delivery_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Store',
    sa.Column('bookstore_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('bookstore_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Author',
    sa.Column('author_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=30), server_default=sa.text("'one'"), nullable=True),
    sa.Column('short_biography', mysql.VARCHAR(length=90), server_default=sa.text("'one'"), nullable=True),
    sa.Column('age', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`age` >= 18)', name=op.f('author_chk_1')),
    sa.PrimaryKeyConstraint('author_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=55), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=55), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`age` >= 14)', name=op.f('user_chk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'User', ['email'], unique=True)
    op.create_table('BookAuthor',
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['Author.author_id'], name=op.f('bookauthor_ibfk_2')),
    sa.ForeignKeyConstraint(['book_id'], ['Book.book_id'], name=op.f('bookauthor_ibfk_1')),
    sa.PrimaryKeyConstraint('book_id', 'author_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Payment',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_date', mysql.DATETIME(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint("(`status` in (_utf8mb4'pending',_utf8mb4'completed',_utf8mb4'failed'))", name=op.f('payment_chk_1')),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], name=op.f('payment_ibfk_1')),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Orders',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_date', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cart_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(`status` in (_utf8mb4'new',_utf8mb4'paid',_utf8mb4'shipped',_utf8mb4'cancelled'))", name=op.f('order_chk_1')),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.cart_id'], name=op.f('orders_ibfk_1')),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Store_Book',
    sa.Column('store_book_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('available_quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.Column('bookstore_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Book.book_id'], name=op.f('store_book_ibfk_2')),
    sa.ForeignKeyConstraint(['bookstore_id'], ['Store.bookstore_id'], name=op.f('store_book_ibfk_1')),
    sa.PrimaryKeyConstraint('store_book_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Review',
    sa.Column('review_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('review_date', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Book.book_id'], name=op.f('review_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name=op.f('review_ibfk_1')),
    sa.PrimaryKeyConstraint('review_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Genre',
    sa.Column('genre_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=155), nullable=True),
    sa.PrimaryKeyConstraint('genre_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
